name: requests from user
on: 
    repository_dispatch: 
        types: [hello]
jobs:
    dispatch:
        runs-on: ubuntu-latest
        steps:
            - run: echo ${{ toJson(github.event) }}